name: Remote Dispatch Action Initiator

on:
  push:
    branches:
      develop
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
#      - name: PING - Dispatch initiating repository event
#        if: github.event.action != 'pong'
#        run: |
#          curl -X POST https://api.github.com/repos/trixt63/AirflowFirstCode \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
#          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
#      - name: ACK - Acknowledge pong from remote repository
#        if: github.event.action == 'pong'
#        run: |
#          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
#          curl -X POST https://api.github.com/repos/trixt63/AirflowFirstCode \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.ACCESS_TOKEN }} \
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
             token: ${{ secrets.ACCESS_TOKEN }}
             repository: trixt63/AirflowFirstCode
             event-type: my-event
             client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'