#name: Update Airflow Submodule
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  update-submodule:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.5.3
#      with:
#        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#    - name: Clone airflow repository
#      run: |
#        git clone git@github.com:<your-username>/airflow.git
#        cd airflow
#        git config user.name "github-actions"
#        git config user.email "github-actions@github.com"
#
#    - name: Update submodule
#      run: |
#        cd airflow
#        git submodule update --remote --merge vmtrace
#        git add vmtrace
#        git commit -m "Update vmtrace submodule to latest commit"
#        git push origin main
