name: Update Airflow workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  update-in-airflow:
    runs-on: ubuntu-latest
    steps:
      - name: Send info to Airflow repo
        run: |
          curl -X POST https://api.github.com/repos/trixt63/AirflowFirstCode/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{
            "event_type": "update-submodule", 
            "client_payload": { 
              "repository": "'"$GITHUB_REPOSITORY"'" 
            }
          }'